create table if not exists public.consultation_requests (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  parent_name text not null,
  child_name text not null,
  child_age text not null,
  email text not null,
  phone text not null,
  city text not null,
  concern text not null,
  page text
);

alter table public.consultation_requests enable row level security;

create policy "Allow public consultation inserts"
on public.consultation_requests
for insert
to anon
with check (true);
